name: Deploy to Railway

on:
  push:
    branches:
      - main  # or your preferred branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      SVC_ID: 18c57678-73cd-4a69-ac3b-6a0bf943e2c2
  # replace with your actual service ID

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh

      - name: Authenticate with Railway
        run: |
          mkdir -p ~/.railway
          echo "$RAILWAY_TOKEN" > ~/.railway/token.json

      - name: Deploy to Railway
        run: railway up --service=18c57678-73cd-4a69-ac3b-6a0bf943e2c2

