name: Deploy to Railway

on:
  push:
    branches:
      - main  # or your preferred branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Install dependencies if needed (example for Python)
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Install Railway CLI (pinned to specific version)
      - name: Install Railway CLI
        run: npm install -g @railway/cli@latest

      - name: Verify Railway CLI
        run: railway --version

      - name: Print Token
        run: echo ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          echo "$RAILWAY_TOKEN" > ~/.railway.token
          railway login --browserless
          railway up